version: '3.8'

services:
  minio:
    image: quay.io/minio/minio
    command: ["server", "/data", "--console-address", ":9001"]
    volumes:
      - minio:/data
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio_Pwd
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: unless-stopped

volumes:
  minio: