version: '3.8'

services:
  minio:
    image: quay.io/minio/minio
    command: ["server", "/data", "--console-address", ":9001"]
    volumes:
      - minio:/data
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio_Pwd
    expose:
      - 9000
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 3s
      timeout: 20s
      retries: 3
  
  configure:
    image: quay.io/minio/mc
    entrypoint: ""
    command: ['/scripts/configure.sh']
    volumes:
      - "./scripts:/scripts"
      - "./samples:/samples"
    environment:
      - ACCESS_URL=http://minio:9000
      - ACCESS_KEY=minio
      - SECRET_KEY=minio_Pwd
      - CONSOLE_ACCESS_KEY=console
      - CONSOLE_SECRET_KEY=console_Pwd
    depends_on:
      minio:
        condition: service_healthy
    restart: 'no'

  nginx:
    image: nginx:1.23
    volumes:
    - ./nginx/templates:/etc/nginx/templates
    ports:
    - "8080:80"
    environment:
    - MINIO_STATIC_BUCKET=tenant1
    - MINIO_HOST=minio:9000
    - NGINX_PORT=80

volumes:
  minio: